### ISSUE TITLE
[Feature]: Xenon Gas Message Channels

### ISSUE THREAD

**Issue by TheDicko** [LRTNZ/KerbalSimpitRevamped#1]
**Describe the solution you'd like**

Complete the resource messages, by adding Xenon gas channels, one for Total and one for stage. Each channel, similarly to every other resource channel, will contain a resourceMessage struct. It can then be parsed using the parseResource function, to be further processed.

**Describe alternatives you've considered**

I have not considered an alternative other than adding additional channels to register to.

**Additional context**
Nothing more to add, other than that i envision we will be able to do everything we can already do with other resources, with Xenon gas.

![123617924_1646446018870818_5682632538642142177_n](https://user-images.githubusercontent.com/72386648/97976514-b0ae3580-1dc2-11eb-8f4e-24ddd8c58409.jpg)

**Comment by TheDicko** [comment]
Sorry for the awful drawing !

**Comment by LRTNZ** [comment]
> 
> 
> Sorry for the awful drawing !

All good - helps get the message across!

**Comment by LRTNZ** [comment]
Right, I did actually make a start on this the other night, just had a couple of exams to get through. Shall get back onto this in a couple of hours.

**Comment by TheDicko** [comment]
Awesome! Happy to test whenever it is ready. My code is setup in anticipation.

**Comment by LRTNZ** [comment]
Finally had a bit of time to update the way the mod is being built, to make it easier to work with on Windows, without having to use Visual Studio.

**Comment by TheDicko** [comment]
> Finally had a bit of time to update the way the mod is being built, to make it easier to work with on Windows, without having to use Visual Studio.

Not a fan of VS?

**Comment by LRTNZ** [comment]
> 
> Not a fan of VS?

Nah not really - I have never really had the time to spend learning it, and what it can do. Also, using VS means there will have to be a bunch of extra junk in the project for it to be happy, which makes the codebase way less friendly to have across multiple machines and the like - or at least that is my understanding of it all.

Also I am quite fond of the simplicity of VS Code, and how versatile it is.

But I have also decided to tweak a few things in the way the development environment for the project should be setup, to make it way easier for multiple developers to work on without constantly having to deal with changing makefile/dependency  paths - the power of symlinks!

**Comment by LRTNZ** [comment]
Finished! Thanks @PBechon
