### ISSUE TITLE
[Feature]: Warp to next manouver message from simpit to ksp

### ISSUE THREAD

**Issue by TheDicko** [LRTNZ/KerbalSimpitRevamped#17]
### A clear and concise description of what you want to happen.

Similar to other messages that are sent from simpit to KSP, you can send one to warp to next manovre if one exists

<br>

### How would it be best that the feature is implemented? What sort of data may need to be sent by the mod to controllers? Would it require a digital signal, or an analogue one? Maybe it needs a terminal command to help use it, or a GUI button?

An accompanied arduino function call, unless it is easier just to use the send function

**Comment by LRTNZ** [comment]
Sounds like a great idea! Will have to have a look into this.

**Comment by LRTNZ** [comment]
Hmmm, how does a Warp Control packet sound?

**Comment by PBechon** [comment]
It sounds great. My idea would be to have a single byte send with an enum of all the actions possible 

- Timewarp to x1
- Timewarp to x2
- ...
- Warp to next maneuver
- Warp to next SOI change
- Warp to apoapsis
- Warp to periapsis

**Comment by TheDicko** [comment]
sounds fantastic!

**Comment by TheDicko** [comment]
@PBechon Would need to consider physics warp too

**Comment by PBechon** [comment]
The API to use is [here](https://kerbalspaceprogram.com/api/class_time_warp.html)

How about 

- Timewarp to x1 (i.e. no timewarp)
- Timewarp to x5
- Timewarp to x10
- Timewarp to x50
- Timewarp to x100
- Timewarp to x1 000
- Timewarp to x10 000
- Timewarp to x100 000
- Timewarp physical to x2
- Timewarp physical to x3
- Timewarp physical to x4
- Timewarp increase to next rate (will use rails or physical depending on current mode)
- Timewarp decrease to previous rate (will use rails or physical depending on current mode)
- Warp to next maneuver
- Warp to next SOI change
- Warp to apoapsis
- Warp to periapsis
- Cancel Auto Warp

All the timewarp command will be ignored if they are not available. Do you think it is useful to send the availability of warp rate to the controller ?

**Comment by TheDicko** [comment]
Looks great. And yeah i guess it would be useful!

**Comment by PBechon** [comment]
This has been merged into a dedicated branch by #28 

The arduino repo has not been updated with @LRTNZ  changes (using rate index instead of rate values for the commands).

@LRTNZ do you want to keep this issue open ?

**Comment by LRTNZ** [comment]
I am pretty sure I updated the arduino side of things? Or at least merged it in. 
In terms of merging in the timewarp support branch into develop, I am waiting to hear more about timewarp to next morning?

**Comment by PBechon** [comment]
@LRTNZ I believe this feature request can be closed, or do you think anything else is needed ?

**Comment by LRTNZ** [comment]
No, I think this is all sorted - thank you!
