### ISSUE TITLE
[Feature]: Add an OutboundPacket for deltaV

### ISSUE THREAD

**Issue by PBechon** [LRTNZ/KerbalSimpitRevamped#2]
**Is your feature request related to a problem? Please describe.**
I'd like to display the remaining deltaV of my rocket on my controler (both stage deltaV and total deltaV).

**Describe the solution you'd like**
I'd like a new outbout message (similar or even using a resourceMessage) to receive the deltaV from the game.

**Describe alternatives you've considered**
No alternative considered as the available fuel is not enough to compute deltaV.

**Comment by LRTNZ** [comment]
Yes, this is certainly high on the list of things to do!

**Comment by PBechon** [comment]
Before tackling this issue, what data seems pertinent to send ? I have the feeling that `FlightGlobals.ActiveVessel.VesselDeltaV` will give a class that gives all the relevant data. So adding a new function in `Telemetry.cs` should be straightforward. The question is what to send.

We could send :
- Total delta V in current situation
- Current Stage deltaV in current situation
- Total/Stage delta V in vacuum
- Total/Stage delta V in atmosphere (ASL)
- Total/Stage burn time
- Current TWR/ISP/Thrust in different situation (actual/vacuum/ASL)

What do you think is useful ?

I would suggest 
- one packet with stage and total delta V in current situation (2 float).
- one packet with stage and total burn time in current situation (2 float).

I'm not sure if it is useful to send data for other situation than the current. What do you think ?

**Comment by TheDicko** [comment]
As an outsider to the dev of Simpit, but someone who benefits from it, i'd say those first 6 things you listed will be of so much use, and would love to see them all implemented.

**Comment by LRTNZ** [comment]
I would agree with the seperation of burn time and deltaV. In terms of total data transferred for the average user it certainly is not the most efficient, but from an architectural point of view it certainly does.

**Comment by PBechon** [comment]
In this case my proposition is to create 3 new messages :

- DeltaV with 2 float : stageDeltaV and totalDeltaV
- DeltaVVacASL with 4 float : stageASLDeltaV, totalASLDeltaV, stageVacDeltaV, totalVacDeltaV
- BurnTime with 1 float : stageBurnTime  and totalBurnTime

The idea is that the first message will be the most used I think. The second one for those who wants all the information. And for the burnTime is does not depend on ASL/Vaccum condition.

What do you think ? If you agree, I can implements those.

**Comment by LRTNZ** [comment]
Hmmm,  Would DeltaVEnviro be clearer? That way it covers both the vacuum and atmospheric environments?
And burn time would need to have 2 floats as well 😄 

But by all means, if you would like to have a go at implementing them, be my guest.

**Comment by PBechon** [comment]
See #13 for a proposal. I used deltaVEnv as you suggested. I made a corresponding PR on the Arduino repository.
