### ISSUE TITLE
[Feature]: Camera pan and camera tools

### ISSUE THREAD

**Issue by TheDicko** [LRTNZ/KerbalSimpitRevamped#21]
### Is it an existing/new feature in the game that would benefit from support by this mod?

It is in the game. The feature i am requesting is similar to holding down right click on the mouse and moving the mouse to pan the camera. By searching camera_position in the api, and seeing this "Vector3d FlightGlobals.camera_position", this seems promising. An additional feature could be to add in controls for camera type (lock, chase , auto) , but personally i have only ever used auto

## Describe the solution you'd like
Similar to controlling rotation of vessel, control panning of the camera.

### A clear and concise description of what you want to happen.

I will use the joysticks as an example. (Feel free to ask which ones but we have discussed them in discord). Push the joystick forward/back to rotate over/under the joystick. Push the joystick left/right to rotate around the craft. Twist the joystick to zoom in / out. And you should be able to send all 3 things as part of the same message (similar to rotation messages) for real 3d ness and so you can go diagonal etc.

### How would it be best that the feature is implemented? What sort of data may need to be sent by the mod to controllers? Would it require a digital signal, or an analogue one? Maybe it needs a terminal command to help use it, or a GUI button?

As above and most definitely analogue.
<br>

### What is the nearest feature in the mod (If there is one), that is along the lines of what you are suggesting?
Rotation  / translation although this is old

**Comment by LRTNZ** [comment]
@TheDicko I have added in zoom support, let me know how you get on with it!

**Comment by LRTNZ** [comment]
Nothing has been said about this, so I will assume everything is fine!

**Comment by TheDicko** [comment]
@LRTNZ Worked fine when i tested it.
