### ISSUE TITLE
[BUG]: Serial stop/start does not restore all functionalities

### ISSUE THREAD

**Issue by PBechon** [LRTNZ/KerbalSimpitRevamped#27]
# Description of the bug

## A clear and concise description of what the bug is

When using '/sim serial stop' and then '/sim serial stop', the function initPorts is called. This function redefine all the elements of onSerialReceivedArray. This mean that all the callback that are defined are erased. This break the SimPit functions that listen for input from Arduino. We need to reload the game to restore those functionalities.

## To Reproduce

1. Launch KSP and load a mission
2. Type '/sim serial stop'
3. Type '/sim serial start'
4. Restart the Arduino
5. Try to use functions to send data to KSP : it is not registered. Reloading the game solve the issue.

## To Solve

When stopping and restarting serial connection, the connection itself should be reset but all the callbacks should not be erased.

**Comment by LRTNZ** [comment]
I have pushed the branch fix/fix-serial-reconnection that should do the trick. There were a couple of things in there that I needed to tweak that prevented the reconnecting controller from binding as intended.

Let me know if it works, and I will merge it in!

**Comment by LRTNZ** [comment]
Fixed!

If it is not, feel free to reopen this issue.

**Comment by TheDicko** [comment]
This may be why i got a unity crash a while ago.
