### ISSUE TITLE
[Feature]: Add orbital information message

### ISSUE THREAD

**Issue by PBechon** [LRTNZ/KerbalSimpitRevamped#33]
I think it would be a good thing to have more information on the orbit than what we currently have (only apoapsis/periapsis altitude). It could be useful for instance to know from the controller if a mission requesting a specific orbit is reached for instance

The orbit can be described with those 5 parameters : 
- Eccentricity 
- Semi major axis 
- inclination
- longitude of ascending node
- argument of periapsis

The eccentricity and the semi-major axis can be recomputed from the apoapsis or the periapsis (or the other way around).

To define the position of the craft on the orbit, on can use the true anomaly (or the mean anomaly).

More information on orbital parameters [here](https://en.wikipedia.org/wiki/Orbital_elements)

We can also add the period of the orbit as a useful information.

All those information can be found within [this class](https://kerbalspaceprogram.com/api/class_orbit.html) in the API.

If we want to send all those information, we need a message with 8 floats (5 for the orbit plus mean anomaly, true anomaly and the period). 

@LRTNZ Do you think a new message with those 8 parameters would be a good addition ?

**Comment by LRTNZ** [comment]
Ok, my question with this one is: do we calculate this stuff, or use Kerbal Engineer Redux...

I am leaning towards us doing it, as it means one less dependency.

**Comment by PBechon** [comment]
I believe everything is readily available in the KSP API, so for this I don't think we need to integrated KER.

**Comment by LRTNZ** [comment]
That sounds good to me then!

**Comment by PBechon** [comment]
Closed as #49 was merged
