### ISSUE TITLE
[Feature]: Add GUI in KSP to show connection state and disconnect/reconnect

### ISSUE THREAD

**Issue by PBechon** [LRTNZ/KerbalSimpitRevamped#4]
**Is your feature request related to a problem? Please describe.**
When developping the Arduino code, it is uploaded to Arduino via the serial link. So the code cannot be uploaded while the Arduino is connected to KSP. This usually mean that I have to restart KSP between each code update and this is tedious (especially with modded KSP).

**Describe the solution you'd like**
I'd like a GUI menu that shows if the Arduino is connected and the option to close the connection (to upload a new Arduino code or disable the controler if something strange happen) and to re-open the connection (to test the new code without having to reload a save).

**Describe alternatives you've considered**
The only option is currently to close the game, upload the code, and relaunch KSP. It is doable but tedious.

**Comment by LRTNZ** [comment]
I did actually right some code that fixed this issue about 2 years ago, and submitted it as a PR to the original repo. It did not use a GUI, as I opted to just do it with an ingame terminal command. I will just have to rework that code to match the recent changes to the Serial code in this mod, and it should be good to go.

**Comment by LRTNZ** [comment]
Right, well now that my code for the runtime connect/disconnect has been added to the Dev branch, I will be looking into this soon!

**Comment by PBechon** [comment]
This has been merged into the dev branch
