### ISSUE TITLE
[BUG]: No SOI message at initialisation

### ISSUE THREAD

**Issue by PBechon** [LRTNZ/KerbalSimpitRevamped#42]
Based on a report on GitHub : when using the SOI message, it is sent when the SOI change but it is undefined until the first SOI change.

If you launch KSP and load a game, no SOI message is send until a SOI change happen. This prevent displaying the current SOI when the game is launched.

**Comment by LRTNZ** [comment]
Should we look at adding some way of sending select messages like the current SOI, when a ship is loaded?
So that the controller can update with all of the values that may change rather infrequently.

**Comment by PBechon** [comment]
Based on my finding, the message is sent each time the SOI change for whatever reason (I did not test it, but it should be OK for ship load). The issue was that there is no check that there is a controller receiving the SOI message so when a controller subscribe for the first time, there is no special case to send the first SOI name.
All the ones after that should be OK.

**Comment by PBechon** [comment]
Closed as #45 is merged
