### ISSUE TITLE
[Feature]: Add outbound message with manoeuver data

### ISSUE THREAD

**Issue by PBechon** [LRTNZ/KerbalSimpitRevamped#5]
**Is your feature request related to a problem? Please describe.**
I'd like to display on my controller data from the planned maneuver : time to maneuver, deltaV of the maneuver, length of the planned burn.

**Describe the solution you'd like**
I'd like an outbound message with all this data regarding the next maneuver :
- time to maneuver
- deltaV of the maneuver
- length of the planned burn

**Describe alternatives you've considered**
No alternative found

**Comment by LRTNZ** [comment]
I will have to take a look to see what the Modding API bindings are for this. Hopefully they exist!

**Comment by PBechon** [comment]
I had a quick look into it. I think by calling `FlightGlobals.ActiveVessel.patchedConicSolver.maneuverNodes` we can access the list of maneuver nodes. Each maneuver has [this API](https://kerbalspaceprogram.com/api/class_maneuver_node.html). So here is my proposal for a new message

```
struct ManeuverData {
  float timeToNextManeuver
  float deltaVNextManeuver
  float durationNextManeuver
  float deltaVTotal
}
```

- The time to next maneuver and deltaV is straighforward from the API. 

- The duration would need to be computed based on current thrust. But if the current stage is not enough to perform the maneuver, the computation will be a little bit more involved as it would mean looking to all the next stages to get the max deltaV and thrust and see all the stages that will be involve in this maneuver. Another solution is to only estimate it based on current stage.

- The deltaV total is the sum of all the deltaV of all maneuvers currently planned. I don't know if it is useful to add a new field to indicate the number of maneuver currently planned.

What do you think ? If we agree on the format, I can start the implementation

**Comment by LRTNZ** [comment]
The solution looks great!
