### ISSUE TITLE
[BUG]: Certain channels freeze up when docking or undocking

### ISSUE THREAD

**Issue by spitfire80** [LRTNZ/KerbalSimpitRevamped#54]
# Certain channels freeze up when docking or undocking

### What feature are you trying to use that is in the documentation, that is not behaving as the documentation says it should/will do?  
<br>

### What have you done to ensure the issue is a bug? Have you tried checking different combinations of button presses for example, to ensure that it is indeed not your controllers code?  
I have contacted rogor via discord and supplied the KSP log.
<br>

### Doesn't happen every time but does pretty often.

 
<br>

## To Reproduce
Dock with another ship with the apsides or velocity displaying. Undock and switch to original ship. The display should no longer update if duplicated.

## Expected behaviour
I would expect the data to update after undocking.

<br>

### What is it in the documentation that leads you to believe the behaviour you are experiencing is unintended. Eg: Is something meant to be returning a specific value, and is never doing that?
<br>

## Additional context
[KSP.log.zip](https://github.com/LRTNZ/KerbalSimpitRevamped/files/6353551/KSP.log.zip)

**Comment by PBechon** [comment]
Probably fixed by de8ee8eaff7b2fd41ca4bcc7efdcda9ac63390c6

Waiting for confirmation before closing

**Comment by spitfire80** [comment]
This has fixed the issue. Tried it for several days and no problems.
