### ISSUE TITLE
[Feature]: Add additional information on horizontal/vertical velocity

### ISSUE THREAD

**Issue by PBechon** [LRTNZ/KerbalSimpitRevamped#6]
**Is your feature request related to a problem? Please describe.**
To help with landing, I'd like to be able to display vertical and horizontal velocity with respect to the terrain. Currently, only the value of the velocity is available and not its decomposition in horizontal/vertical components.

**Describe the solution you'd like**
A new outbound message (to avoid breaking the retro-compatibility) with the horizontal/vertical components of the velocity with respect to the terrain.

**Describe alternatives you've considered**
No alternative found.

**Comment by PBechon** [comment]
It seems that vertical speed is part of the current message. The horizontal speed can probably be computed with surface and vertical velocity. So no change needed here.

**Comment by LRTNZ** [comment]
Maybe, will take a look into this some more, as I believe there are some other velocity components that may be useful.
