### ISSUE TITLE
[Feature]:Make it possible/easier to get information from the game

### ISSUE THREAD

**Issue by Lucaspec72** [LRTNZ/KerbalSimpitRevamped#7]
**Is your feature request related to a problem? Please describe.**
I'm planning to show the action groups & CAG's state (on/off) from the arduino but i can't find how to the the state of the CAG.  also action groups are not the only things to have this problem, but i'm focusing on CAGs.
What is the issue that you are facing, that you would like resolved?
Can't get the state of things like CAG on the arduino.
How would it benefit players?
Would make it WAY easier to use/manage CAGs with simpit.

**Describe the solution you'd like**
Add the CAGs in "ACTIONSTATUS_MESSAGE".
How would it be best that the feature is implemented? What sort of data may need to be sent by the mod to controllers? Would it require a digital signal, or an analogue one?
pretty much just make CAG work like the action groups (example : lights, gears, brakes)
Would it need a terminal command to help use it, or a GUI button?
no
**Describe alternatives you've considered**
use switches instead of buttons (or make code to make a button work like a switch) to make sure it's either ON or OFF using the switch's state and set the action group to that value every loop to make sure it doesn't desync.
What about the current features of the program do not quite, if at all, allow you to implement/carry out what you would like to do? What is the nearest feature in the mod (If there is one), that is along the lines of what you are suggesting?
the previously stated "ACTIONSTATUS_MESSAGE" already does pretty much exactly what i want, it just can't get info from CAGs (or if there is i'm very sorry but i couldn't find a way anywhere)
**Additional context**
i planned to have most of the stuff in my controller sync info from the game without having to add too much code that could lead to desync of values, that include action groups, i would like to just set a custom character to the CAG's state (0/1).

**Comment by LRTNZ** [comment]
Hey sorry for the delay in response. This is something that I believe is currently being worked on by one of the other contributers!

**Comment by PBechon** [comment]
I believe that was integrated with PR #22 and this is working at least without AGExt. We could probably close this issue.

**Comment by Lucaspec72** [comment]
i'l have to take your word for it since i don't know what this is but i'm gonna close the issue before i forget to do it.

**Comment by TheDicko** [comment]
Yes this is now merged into develop
